"""Request correlation and structured JSON logging.

Rules (see docs/architecture.md, "可观测性"):
- The request id is generated by the server; a client-supplied ``X-Request-ID`` is ignored.
- Logs are one JSON object per line on stdout, standard library only.
- Never log headers, bodies, credentials, or ``str(exception)``. Exceptions are reduced to
  their type and ``file:line:function`` frames; only exact types registered through
  ``allow_exception_message`` may also log their message.
"""

import json
import logging
import time
import traceback
from collections.abc import MutableMapping
from contextvars import ContextVar
from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4

from starlette.types import ASGIApp, Message, Receive, Scope, Send

REQUEST_ID_HEADER = "X-Request-ID"
ACCESS_LOGGER = logging.getLogger("easyaudit.access")
APP_LOGGER = logging.getLogger("easyaudit.app")

_MAX_STACK_FRAMES = 40

_request_id: ContextVar[str | None] = ContextVar("request_id", default=None)
# Mutable holder: sync dependencies run in a copied context, so they must mutate a shared
# object rather than set a contextvar for the middleware to see the value.
_actor: ContextVar[dict[str, str | None] | None] = ContextVar("actor", default=None)

_SAFE_MESSAGE_EXCEPTIONS: set[type[BaseException]] = set()


def current_request_id() -> str | None:
    return _request_id.get()


def bind_actor(organization_id: UUID, actor_user_id: UUID) -> None:
    holder = _actor.get()
    if holder is not None:
        holder["organization_id"] = str(organization_id)
        holder["actor_user_id"] = str(actor_user_id)


def allow_exception_message(exception_type: type[BaseException]) -> None:
    """Explicitly declare that this exact type's message never carries SQL, parameters or PII."""
    _SAFE_MESSAGE_EXCEPTIONS.add(exception_type)


class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, Any] = {
            "timestamp": datetime.fromtimestamp(record.created, UTC).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
            "request_id": _request_id.get(),
        }
        fields = getattr(record, "fields", None)
        if isinstance(fields, dict):
            payload.update(fields)
        if record.exc_info and record.exc_info[1] is not None:
            payload.update(describe_exception(record.exc_info[1]))
        return json.dumps(payload, default=str, ensure_ascii=False)


def describe_exception(exc: BaseException) -> dict[str, Any]:
    """Type and frames only. ``str(exc)`` can embed SQL statements and bound parameters."""
    exception_type = type(exc)
    described: dict[str, Any] = {
        "exception_type": f"{exception_type.__module__}.{exception_type.__qualname__}",
        "stack": [
            f"{frame.filename}:{frame.lineno}:{frame.name}"
            for frame in traceback.extract_tb(exc.__traceback__)[-_MAX_STACK_FRAMES:]
        ],
    }
    if exception_type in _SAFE_MESSAGE_EXCEPTIONS:
        described["exception_message"] = str(exc)
    return described


def build_log_config(level: str) -> dict[str, Any]:
    """dictConfig for uvicorn's ``log_config``; uvicorn's own access log is disabled."""
    handler = {"class": "logging.StreamHandler", "formatter": "json", "stream": "ext://sys.stdout"}
    return {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {"json": {"()": f"{__name__}.JsonFormatter"}},
        "handlers": {"stdout": handler},
        "loggers": {
            "uvicorn": {"handlers": ["stdout"], "level": level, "propagate": False},
            "uvicorn.error": {"level": level},
            "uvicorn.access": {"handlers": [], "level": "CRITICAL", "propagate": False},
            "easyaudit": {"handlers": ["stdout"], "level": level, "propagate": False},
            # MigrationContext logs at INFO on every readiness probe.
            "alembic": {"level": "WARNING"},
        },
        "root": {"handlers": ["stdout"], "level": level},
    }


class RequestContextMiddleware:
    """Pure ASGI middleware: request id, access log, and the unhandled-exception boundary."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = str(uuid4())
        request_token = _request_id.set(request_id)
        actor: dict[str, str | None] = {"organization_id": None, "actor_user_id": None}
        actor_token = _actor.set(actor)
        started = time.perf_counter()
        status_code = 500
        response_started = False

        async def send_with_request_id(message: Message) -> None:
            nonlocal status_code, response_started
            if message["type"] == "http.response.start":
                response_started = True
                status_code = message["status"]
                headers = list(message.get("headers", []))
                headers.append((REQUEST_ID_HEADER.lower().encode(), request_id.encode()))
                message = {**message, "headers": headers}
            await send(message)

        try:
            await self.app(scope, receive, send_with_request_id)
        except Exception as exc:
            APP_LOGGER.error("unhandled_exception", exc_info=exc)
            status_code = 500
            if not response_started:
                await _send_internal_error(send, request_id)
        finally:
            route = scope.get("route")
            ACCESS_LOGGER.info(
                "request",
                extra={
                    "fields": {
                        "method": scope["method"],
                        "route": getattr(route, "path", None),
                        "status_code": status_code,
                        "latency_ms": round((time.perf_counter() - started) * 1000, 2),
                        **actor,
                    }
                },
            )
            _actor.reset(actor_token)
            _request_id.reset(request_token)


async def _send_internal_error(send: Send, request_id: str) -> None:
    body = json.dumps({"detail": "Internal Server Error", "request_id": request_id}).encode()
    headers: MutableMapping[bytes, bytes] = {
        b"content-type": b"application/json",
        b"content-length": str(len(body)).encode(),
        REQUEST_ID_HEADER.lower().encode(): request_id.encode(),
    }
    await send({"type": "http.response.start", "status": 500, "headers": list(headers.items())})
    await send({"type": "http.response.body", "body": body})
