"""Request correlation and structured JSON logging.

Rules (see docs/architecture.md, "可观测性"):
- The request id is generated by the server; a client-supplied ``X-Request-ID`` is ignored.
- Logs are one JSON object per line on stdout, standard library only.
- Never log headers, bodies, credentials, or ``str(exception)``. Exceptions are reduced to
  their type, cause types and ``file:line:function`` frames; there is no field for a message.
"""

import json
import logging
import time
import traceback
from collections.abc import MutableMapping
from contextvars import ContextVar
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any
from uuid import UUID, uuid4

import psycopg
from starlette.types import ASGIApp, Message, Receive, Scope, Send

REQUEST_ID_HEADER = "X-Request-ID"
ACCESS_LOGGER = logging.getLogger("easyaudit.access")
PROBE_ROUTES = frozenset({"/health/live", "/health/ready"})
APP_LOGGER = logging.getLogger("easyaudit.app")

_MAX_STACK_FRAMES = 40

_request_id: ContextVar[str | None] = ContextVar("request_id", default=None)
# Mutable holder: sync dependencies run in a copied context, so they must mutate a shared
# object rather than set a contextvar for the middleware to see the value.
_actor: ContextVar[dict[str, str | None] | None] = ContextVar("actor", default=None)


def current_request_id() -> str | None:
    return _request_id.get()


def bind_actor(organization_id: UUID, actor_user_id: UUID) -> None:
    holder = _actor.get()
    if holder is not None:
        holder["organization_id"] = str(organization_id)
        holder["actor_user_id"] = str(actor_user_id)


# Runtime backstop for the "no sensitive data in logs" rule: only these keys from
# `extra={"fields": ...}` are ever rendered. Anything else is dropped (its key is reported in
# `dropped_fields`, its value never is). Exception details do not go through this list; they
# come from `ExceptionDetails`, which `describe_exception` alone builds.
ALLOWED_FIELDS = frozenset(
    {
        "method",
        "route",
        "status_code",
        "latency_ms",
        "error",
        "organization_id",
        "actor_user_id",
        "component",
        "reason",
        "current_revision",
        "expected_revision",
        "throttle_scope",
        "storage_key",
        "export_format",
        "row_count",
    }
)
_MAX_VALUE_CHARS = 200
_MAX_LIST_ITEMS = 20
_DROPPED = "[dropped]"


def _bound_value(value: object) -> object:
    if value is None or isinstance(value, bool | int | float):
        return value
    if isinstance(value, str):
        return value[:_MAX_VALUE_CHARS]
    if isinstance(value, list | tuple) and all(isinstance(item, str) for item in value):
        return [item[:_MAX_VALUE_CHARS] for item in value[:_MAX_LIST_ITEMS]]
    return _DROPPED


@dataclass(frozen=True, slots=True)
class ExceptionDetails:
    exception_type: str
    exception_chain: tuple[str, ...]
    stack: tuple[str, ...]


class JsonFormatter(logging.Formatter):
    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, Any] = {
            "timestamp": datetime.fromtimestamp(record.created, UTC).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
            "request_id": _request_id.get(),
        }
        fields = getattr(record, "fields", None)
        if isinstance(fields, dict):
            dropped = sorted(str(key) for key in fields if key not in ALLOWED_FIELDS)
            payload.update(
                {key: _bound_value(value) for key, value in fields.items() if key in ALLOWED_FIELDS}
            )
            if dropped:
                payload["dropped_fields"] = dropped[:_MAX_LIST_ITEMS]
        details = getattr(record, "exception_details", None)
        if record.exc_info and record.exc_info[1] is not None:
            details = describe_exception(record.exc_info[1])
        if isinstance(details, ExceptionDetails):
            payload["exception_type"] = details.exception_type
            payload["exception_chain"] = list(details.exception_chain)
            payload["stack"] = list(details.stack)
        return json.dumps(payload, default=str, ensure_ascii=False)


def describe_exception(exc: BaseException) -> ExceptionDetails:
    """Type and frames only. ``str(exc)`` can embed SQL statements and bound parameters."""
    exception_type = type(exc)
    return ExceptionDetails(
        exception_type=f"{exception_type.__module__}.{exception_type.__qualname__}",
        exception_chain=tuple(_chain_types(exc)),
        stack=tuple(
            f"{frame.filename}:{frame.lineno}:{frame.name}"
            for frame in traceback.extract_tb(exc.__traceback__)[-_MAX_STACK_FRAMES:]
        ),
    )


def _chain_types(exc: BaseException) -> list[str]:
    """Types of ``__cause__``/``__context__`` ancestors; their messages are never logged."""
    chain: list[str] = []
    current = exc.__cause__ or exc.__context__
    while current is not None and len(chain) < 5:
        chain.append(f"{type(current).__module__}.{type(current).__qualname__}")
        current = current.__cause__ or current.__context__
    return chain


def build_log_config(level: str) -> dict[str, Any]:
    """dictConfig for uvicorn's ``log_config``; uvicorn's own access log is disabled."""
    # Third-party/protocol loggers never go below INFO: at DEBUG, libraries may log raw
    # request data (query strings, Cookie, Authorization).
    third_party_level = "INFO" if level == "DEBUG" else level
    handler = {"class": "logging.StreamHandler", "formatter": "json", "stream": "ext://sys.stdout"}
    return {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {"json": {"()": f"{__name__}.JsonFormatter"}},
        "handlers": {"stdout": handler},
        "loggers": {
            "uvicorn": {"handlers": ["stdout"], "level": third_party_level, "propagate": False},
            "uvicorn.error": {"level": third_party_level},
            "uvicorn.access": {"handlers": [], "level": "CRITICAL", "propagate": False},
            "easyaudit": {"handlers": ["stdout"], "level": level, "propagate": False},
            # MigrationContext logs at INFO on every readiness probe.
            "alembic": {"level": "WARNING"},
        },
        "root": {"handlers": ["stdout"], "level": third_party_level},
    }


class RequestContextMiddleware:
    """Pure ASGI middleware: request id, access log, and the unhandled-exception boundary."""

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = str(uuid4())
        request_token = _request_id.set(request_id)
        actor: dict[str, str | None] = {"organization_id": None, "actor_user_id": None}
        actor_token = _actor.set(actor)
        started = time.perf_counter()
        status_code = 500
        response_started = False
        failed = False

        async def send_with_request_id(message: Message) -> None:
            nonlocal status_code, response_started
            if message["type"] == "http.response.start":
                response_started = True
                status_code = message["status"]
                headers = list(message.get("headers", []))
                headers.append((REQUEST_ID_HEADER.lower().encode(), request_id.encode()))
                message = {**message, "headers": headers}
            await send(message)

        try:
            await self.app(scope, receive, send_with_request_id)
        except Exception as exc:
            failed = True
            timeout_kind = database_timeout_kind(exc)
            if timeout_kind is not None:
                APP_LOGGER.warning(
                    "database_timeout",
                    extra={
                        "fields": {"reason": timeout_kind},
                        "exception_details": describe_exception(exc),
                    },
                )
            else:
                APP_LOGGER.error("unhandled_exception", exc_info=exc)
            # Once the response has started, the status line is already on the wire
            # (e.g. a background task or a stream failed later); never rewrite it.
            if not response_started:
                if timeout_kind is not None:
                    status_code = 503
                    await _send_database_unavailable(send, request_id)
                else:
                    status_code = 500
                    await _send_internal_error(send, request_id)
        finally:
            route = scope.get("route")
            route_path = getattr(route, "path", None)
            # Successful orchestrator probes run every few seconds; keep them out of INFO.
            probe_ok = route_path in PROBE_ROUTES and 200 <= status_code < 300
            ACCESS_LOGGER.log(
                logging.DEBUG if probe_ok else logging.INFO,
                "request",
                extra={
                    "fields": {
                        "method": scope["method"],
                        "route": route_path,
                        "status_code": status_code,
                        "error": failed,
                        "latency_ms": round((time.perf_counter() - started) * 1000, 2),
                        **actor,
                    }
                },
            )
            _actor.reset(actor_token)
            _request_id.reset(request_token)


DATABASE_RETRY_AFTER_SECONDS = 1


def database_timeout_kind(exc: BaseException) -> str | None:
    """`statement_timeout` / `lock_timeout` expiry, as raised through SQLAlchemy or directly.

    Both are transient contention, not a stale lifecycle: the request is mapped to 503 with
    Retry-After (not 409, which tells clients to refresh stale data).
    """
    current: BaseException | None = exc
    for _ in range(5):
        if current is None:
            return None
        if isinstance(current, psycopg.errors.QueryCanceled):
            return "statement_timeout"
        if isinstance(current, psycopg.errors.LockNotAvailable):
            return "lock_timeout"
        current = getattr(current, "orig", None) or current.__cause__
    return None


async def _send_database_unavailable(send: Send, request_id: str) -> None:
    body = json.dumps(
        {"detail": "Database temporarily unavailable; retry", "request_id": request_id}
    ).encode()
    headers: MutableMapping[bytes, bytes] = {
        b"content-type": b"application/json",
        b"content-length": str(len(body)).encode(),
        b"retry-after": str(DATABASE_RETRY_AFTER_SECONDS).encode(),
        REQUEST_ID_HEADER.lower().encode(): request_id.encode(),
    }
    await send({"type": "http.response.start", "status": 503, "headers": list(headers.items())})
    await send({"type": "http.response.body", "body": body})


async def _send_internal_error(send: Send, request_id: str) -> None:
    body = json.dumps({"detail": "Internal Server Error", "request_id": request_id}).encode()
    headers: MutableMapping[bytes, bytes] = {
        b"content-type": b"application/json",
        b"content-length": str(len(body)).encode(),
        REQUEST_ID_HEADER.lower().encode(): request_id.encode(),
    }
    await send({"type": "http.response.start", "status": 500, "headers": list(headers.items())})
    await send({"type": "http.response.body", "body": body})
